### ISSUE TITLE
Add git commands in git-cheatsheet.md file

### ISSUE THREAD

**Issue by crescentpartha** [crescentpartha/CheatSheets-for-Developers#1]
**Describe the content type**
> Commonly used git commands need to be added in the git cheatsheet

**Expected tasks**
> add git commands

`Participate the hacktoberfest-2022`

**Comment by beheradibas** [comment]
HI @crescentpartha 
I would like to work on this.

**Comment by ArchitKumar-13** [comment]
Hi @crescentpartha I would like to know in Cheatsheets/ folder, do we need to make another file for git commands or we can update that existing file?
please do let me know...

**Comment by crescentpartha** [comment]
@ArchitKumar-13, [CheatSheets](https://github.com/crescentpartha/CheatSheets-for-Developers/tree/main/CheatSheets) folder is the collection of `all individuals' cheat sheets` files. So, if you want to add more git commands then modify only the `git-cheatsheet.md` file. One more thing, always `make a PR with little changes`. It will help the maintainer **quickly review and merge** the pull request.
