### ISSUE TITLE
Cheat Sheet for C++

### ISSUE THREAD

**Issue by anu-phoenix** [crescentpartha/CheatSheets-for-Developers#106]
**Descriptions**
Want to add cheatsheet for C++ STL

**Expected behavior**
Adding Basic STL functions for Vector, Set, Map, and many more.

Please assign this to me under Hacktoberfest22.

**Comment by crescentpartha** [comment]
Please, follow the [contributing guidelines](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md) and [this comment](https://github.com/crescentpartha/CheatSheets-for-Developers/issues/91#issuecomment-1286794226) before introducing new cheat sheet. @anu-phoenix
