### ISSUE TITLE
Add CONTRIBUTE.md

### ISSUE THREAD

**Issue by MohammadRehanPatel** [crescentpartha/CheatSheets-for-Developers#132]
**Is your feature request related to a problem or a new feature? Please describe.
This will describe the steps that how users can contribute to your project

**Describe the solution you'd like
This will describe the steps that how users can contribute to your project; this will make users easier in contribution

**Additional context**
add hacktoberfest tag

**Comment by crescentpartha** [comment]
[contributing guidelines](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md) is already exist. @MohammadRehanPatel
