### ISSUE TITLE
Update Conda Command cheatsheet 

### ISSUE THREAD

**Issue by nikhilbuts** [crescentpartha/CheatSheets-for-Developers#163]
**Is your feature request related to a problem or a new feature? Please describe.**
> A clear and concise description of what the problem or feature is.

**Describe the solution you'd like**
> A clear and concise description of what you want to happen.

**Additional context**
> Add any other context or **screenshots** about the feature request here.

**Comment by nikhilbuts** [comment]
@CiroMeiraLins 

https://github.com/crescentpartha/CheatSheets-for-Developers/pull/162

Please Review above PR.

Thanks!

**Comment by Tanucode** [comment]
may I add vim (text editors for unix) cheatsheet?
