### ISSUE TITLE
Add a command to view all branches in git CheatSheet

### ISSUE THREAD

**Issue by hemant-sw** [crescentpartha/CheatSheets-for-Developers#24]
Hi !! .. 
In Git CheatSheet for Developers in section of Branching & Merging it will be great if we add how we can view all the list of Branches

If you Think this can be added I am ready to work on that issue.

Thankyou.

**Comment by crescentpartha** [comment]
**Carry on.** @hemant-sw

**Comment by hemant-sw** [comment]
@crescentpartha I am about to push my work  but here you marked as closed ??
