### ISSUE TITLE
Add keyboard shortcuts for VSCode CheatSheet

### ISSUE THREAD

**Issue by crescentpartha** [crescentpartha/CheatSheets-for-Developers#39]
**Describe the content type**
> Add keyboard shortcuts for `VSCode CheatSheet`

**Expected behavior**
> Add commonly used `keyboard shortcuts for VSCode Editor` to boost your productivity.

**Screenshots or Links**
> You can add more keyboard shortcuts in [vscode-cheatsheet.md](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/CheatSheets/vscode-cheatsheet.md) for VSCode Editor

Fill free to `contribute` in this CheatSheet and take a part in an `open-source project`.

**Comment by Sakshi-75** [comment]
Hi @crescentpartha ,
Can I work on this?

**Comment by crescentpartha** [comment]
Obviously, create a pull request to contribute under this issue. @Sakshi-75
