### ISSUE TITLE
Add keyboard shortcuts for Chrome DevTools CheatSheet

### ISSUE THREAD

**Issue by crescentpartha** [crescentpartha/CheatSheets-for-Developers#40]
**Describe the content type**
> Add keyboard shortcuts for `Chrome DevTools CheatSheet`

**Expected behavior**
> Add commonly used `keyboard shortcuts for Chrome DevTools` to boost your productivity.

**Screenshots or Links**
> You can add more keyboard shortcuts in [chrome-devtools-cheatsheet.md](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/CheatSheets/chrome-devtools-cheatsheet.md) for Chrome DevTools.

---

Please, fill free to contribute to this project. Anyone including `newcomers` can make a contribution to this repo by adding `basic Commands` or `Keyboard Shortcuts` or `tags, attributes, and properties` and take a part in an `open-source project`. 
Please, give a `star` to support this project.
<br />

**Comment by satyamrs00** [comment]
hey can you assign this to me ?
i am working on this

**Comment by crescentpartha** [comment]
Please, directly create a `pull request`. @satyamrs00
