### ISSUE TITLE
Add keyboard shortcuts for windows-cheatsheet.md file

### ISSUE THREAD

**Issue by crescentpartha** [crescentpartha/CheatSheets-for-Developers#41]
**Describe the content type**
> Add keyboard shortcuts for `windows-cheatsheet.md`

**Expected behavior**
> Add commonly used `keyboard shortcuts` for `windows-cheatsheet` to `boost your productivity`.

**Screenshots or Links**
> You can add more keyboard shortcuts in [windows-cheatsheet.md](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/CheatSheets/windows-cheatsheet.md).

Fill free to `contribute` in this CheatSheet and take a part in an `open-source project`.

**Comment by imran1509** [comment]
Hey can I work on this? can you assign this to me?

**Comment by SaumyaBhushan** [comment]
Hey @crescentpartha I have added few more commands. Can it be merged?
