### ISSUE TITLE
README.md change to add all new contributors

### ISSUE THREAD

**Issue by devwander** [crescentpartha/CheatSheets-for-Developers#47]
**Describe the content**
> Add new contributors to the repository's README.md

>If possible I would like this activity to be assigned to me

**Comment by imran1509** [comment]
Can I work on this? Can you assign it to me?

**Comment by imran1509** [comment]
Should i make a workflow to update readme regularly on a specific interval?

**Comment by crescentpartha** [comment]
> but What is the issue? in which file? I am totally new to this so can you help me little

Everything is ok. Just contributors' profiles are updated in the `README.md` file with a delay of 1 or 2 days delay. 
We think to make it faster like `real-time updates` when new contributors add to this project, it should also display in the `README.md` file consecutively.

**Comment by devwander** [comment]
@crescentpartha, I was studying ways to make these changes automatically and I found the github api, but I still can't use it and I'm not sure if it's due to something that has to be configured in the repository. Could you take a look?

https://docs.github.com/pt/rest/collaborators/collaborators#list-repository-collaborators
