### ISSUE TITLE
Add more html tags and attributes in html-cheatsheet.md file

### ISSUE THREAD

**Issue by crescentpartha** [crescentpartha/CheatSheets-for-Developers#81]
**Descriptions**
> add more `html tags and attributes`

**Expected behavior**
> Enrich the [html-cheatsheet.md](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/CheatSheets/html-cheatsheet.md) file by adding more frequently used html tags and attributes.

**Screenshots or Links**
> If applicable, add **screenshots** or a modified **UI link** to help explain your contribution.

---

Please, fill free to contribute to this project. Anyone including `newcomers` can make a contribution to this repo by adding `basic Commands` or `Keyboard Shortcuts` or `tags and attributes`. Please, give a `star` to support this project.

**Comment by abhi87374** [comment]
assign this to me...

**Comment by amanaggarwal06** [comment]
Hey, I want to work on this.
Can you please assign it to me @crescentpartha?
