### ISSUE TITLE
Add cheatsheets for Java

### ISSUE THREAD

**Issue by dab07** [crescentpartha/CheatSheets-for-Developers#91]
## New CheatSheet
Add Java Programming Language CheatSheet in CheatSheets folder

**Comment by deepaksuthar40128** [comment]
can i work on it?

**Comment by crescentpartha** [comment]
**Some Instructions:**
- Please, give the `tabular format` like [git-cheatsheet.md](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/CheatSheets/git-cheatsheet.md), It will be better to visualize and understand the whole cheatsheet. 
- File naming convention:  `javas-cheatsheet.md`
- Add your `java-cheatsheet.md` file in `README.md` file.

 Example of `Tabular format`:
## String Methods

| Methods | Descriptions |
| ---------- | -------------  |
| charAt() | Returns a character at a specified position inside a string |
| charCodeAt() | Gives you the unicode of character at that position |

Thanks, @dab07
