### ISSUE TITLE
Add cheatsheet for Linux command line.

### ISSUE THREAD

**Issue by lukedev820** [crescentpartha/CheatSheets-for-Developers#96]
**Describe the solution you'd like**
Many developers may have to use the Linux command line at some point in their career. I think a cheat sheet with all the commonly used commands that they may need to use should be created as it can often be hard to remember them all when starting out (trust me i was there at some point)

 

**Additional context**
I've been using Linux for about 2 years now and would be more than happy to create a cheat sheet with a bunch of necessary commands maybe ordered as so:

- File Commands
- File Permissions
- SSH
- System Info
- Keyboard Shortcuts

**Comment by lukedev820** [comment]
Please assign me to this issue also!

**Comment by crescentpartha** [comment]
Please, follow the [contributing guidelines](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md) and [this comment](https://github.com/crescentpartha/CheatSheets-for-Developers/issues/91#issuecomment-1286794226) before introducing new cheat sheet. @lukedev820
